apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
spec:
  type: NodePort
  selector:
    app: nextjs-app # Must match the labels in the deployment
  ports:
    - protocol: TCP
      port: 80 # Port inside the cluster
      targetPort: 3000 # Port on the container
      nodePort: 30080 # Port to access from outside the 
      

      